dhammatalks:
  master_url: "https://www.dhammatalks.org/suttas/index_mobile.html"
  base_url: "https://www.dhammatalks.org"
  books_of_interest: ["DN", "MN", "SN", "AN", "KN"]
  avoid_in_url: ["histor", "endn", "bibl", "app", "ackn", "intro", "epi", "prol", "syll"]

concept_extraction:
  model_id: "deepseek-chat" # deepseek-chat or gemini-2.5-flash
  mode: "discovery" # fixed or discovery
  temperature: 1
  output_path_template: "data/03_kg_components/raw_concepts_{mode}_{model_id}.jsonl"
  log_path_template: "logs/concept_extraction_skipped_{mode}_{model_id}.jsonl"
  base_prompt_beginning: |
    You are an expert data extractor specializing in Buddhist philosophy and the Pali Canon. Your primary function is to analyze a Sutta text and identify all significant conceptual terms that will serve as nodes in a knowledge graph. Precision, adherence to the text, and correct JSON formatting are paramount.

    ## Core Rules:
    1.  **Text-Only Grounding:** All extracted concepts MUST be directly present in or clearly implied by the provided text. Do not introduce any external Buddhist knowledge or interpretations.
    2.  **Relevance Filter:** Extract only terms that are thematically significant to the Sutta's core message. Ignore incidental details (e.g., "a monk sat down," "the time of day"). Focus on figures, places, practices, mental states, and doctrinal concepts.
    3.  **Focus on Concepts Only:** Your task is ONLY to identify the concepts (nodes). You are NOT to extract relationships between them in this step.

    ---
  discovery_instructions: |
    ## ANALYSIS INSTRUCTIONS

    1.  For each significant concept you identify in the text, create a JSON object with the following three keys:
        *   `"concept_name"`: A concise, normalized name for the concept (e.g., use "The Five Hindrances", not "five hindrances").
        *   `"concept_type"`: A concise and logical category for the concept that you must generate yourself. **Do not use a predefined list.** Instead, derive the type by following these principles:
            1.  **Functional Analysis:** Determine the concept's role in the text. Is it a person/being (`Person`, `Deity`)? A location (`Place`, `CosmicRealm`)? A core teaching (`DoctrinalConcept`)? An internal experience (`MentalState`)? A specific action or method (`Practice`)? A sequence of events or causality (`Process`)?
            2.  **Consistency is Key:** Strive for consistency across the entire text. If you classify one city as `Place`, classify all other cities and groves as `Place`.
            3.  **Use PascalCase:** The type name must be in PascalCase (e.g., `DoctrinalConcept`, `MentalState`).
        *   `"evidence_quote"`: The specific sentence or phrase from the text that directly mentions or defines this concept. This is crucial for verification.
    2.  Combine all the individual JSON objects for the Sutta into a single list.
    3.  Place this list inside a parent JSON object under the key `"concepts"`.

    ---
  fixed_instructions: |
    ## ANALYSIS INSTRUCTIONS

    1.  For each significant concept you identify in the text, create a JSON object with the following three keys:
        *   `"concept_name"`: A concise, normalized name for the concept (e.g., use "The Five Hindrances", not "five hindrances").
        *   `"concept_type"`: The most fitting category. Choose ONLY from this list: [Person, Deity, Place, DoctrinalConcept, MentalState, Practice, Process, Group].
        *   `"evidence_quote"`: The specific sentence or phrase from the text that directly mentions or defines this concept. This is crucial for verification.
    2.  Combine all the individual JSON objects for the Sutta into a single list.
    3.  Place this list inside a parent JSON object under the key `"concepts"`.

    ---
  base_prompt_end: |
    ## EXAMPLE

    **Input Text:**
    "On one occasion the Blessed One was staying at Sāvatthī in Jeta’s Grove. There he said: 'Monks, the development of mindfulness leads to the abandoning of the five hindrances. This is the path to Nibbāna.'"

    **Correct Output:**
    (Note: In this case, the discovered types may be similar to the old list, but they were generated based on principle, not chosen from a fixed set.)
    {
      "concepts": [
        {
          "concept_name": "The Blessed One",
          "concept_type": "Person",
          "evidence_quote": "On one occasion the Blessed One was staying at Sāvatthī in Jeta’s Grove."
        },
        {
          "concept_name": "Sāvatthī",
          "concept_type": "Place",
          "evidence_quote": "On one occasion the Blessed One was staying at Sāvatthī..."
        },
        {
          "concept_name": "Development of Mindfulness",
          "concept_type": "Practice",
          "evidence_quote": "Monks, the development of mindfulness leads to the abandoning of the five hindrances."
        },
        {
          "concept_name": "The Five Hindrances",
          "concept_type": "DoctrinalConcept",
          "evidence_quote": "...leads to the abandoning of the five hindrances."
        },
        {
          "concept_name": "Nibbāna",
          "concept_type": "DoctrinalConcept",
          "evidence_quote": "This is the path to Nibbāna."
        }
      ]
    }    
    ---

    ## FINAL INSTRUCTIONS
    Now, perform this analysis on the following Sutta text. Ensure your final output is ONLY the single, valid JSON object as shown in the example. Do not include any explanatory text or markdown code fences.
concept_normalization:
  mode: "hybrid" # hybrid (cluster on concept and evidence) or name (cluster on concept only)
  embedding_model_id: "all-MiniLM-L12-v2"
  min_community_size: 2
  threshold: 0.75 # Cosine similarity threshold
  output_path_template: "data/04_kg_components/clusters_from_{extraction_model_id}_norm_{normalization_mode}_{embedding_model_id}.json"

output_paths:
  raw_data: "data/01_raw/dhammatalks_suttas.jsonl"